# Generated by Django 5.2 on 2026-02-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_username_sshcredential_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vm",
            name="networking",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
