# Generated by Django 5.2 on 2026-02-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_vm_networking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vm",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
