# Generated by Django 5.2 on 2026-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_vm_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="vm",
            name="user_name",
            field=models.CharField(default="root", max_length=120),
        ),
    ]
