# Generated by Django 5.2 on 2026-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_vm_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sshcredential",
            name="key_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/inventory_ssh_keys/"
            ),
        ),
    ]
