# Generated by Django 5.2 on 2026-02-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_sshcredential_key_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sshcredential",
            name="key_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/inventory/inventory_ssh_keys/"
            ),
        ),
    ]
