# Generated by Django 5.2 on 2026-02-17 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_sshcredential_key_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vm",
            name="managed_containers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="vm",
            name="system_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="SSHAccessHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="celery_task", max_length=64)),
                ("scenario_name", models.CharField(blank=True, max_length=120)),
                ("phase_name", models.CharField(blank=True, max_length=120)),
                ("action_type", models.CharField(blank=True, max_length=120)),
                ("command", models.TextField(blank=True, default="")),
                ("success", models.BooleanField(default=False)),
                ("returncode", models.IntegerField(default=0)),
                ("stdout", models.TextField(blank=True, default="")),
                ("stderr", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ssh_access_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ssh_access_history",
                        to="inventory.vm",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="inventory_s_created_f03da7_idx"
                    ),
                    models.Index(
                        fields=["source"], name="inventory_s_source_283393_idx"
                    ),
                    models.Index(
                        fields=["scenario_name", "phase_name"],
                        name="inventory_s_scenari_8e4b92_idx",
                    ),
                ],
            },
        ),
    ]
