# Generated by Django 5.2 on 2026-02-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_vm_managed_containers_vm_system_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vm",
            name="group_name",
            field=models.CharField(default="default", max_length=120),
        ),
    ]
