# Generated by Django 5.2 on 2026-02-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_vm_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vm",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
