# Generated by Django 5.2 on 2026-02-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_provisioning", "0008_provisioningvm_icopa_config"),
        ("inventory", "0010_vm_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="vm",
            name="auto_provisioned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vm",
            name="cloud_provisioning_vm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_vms",
                to="cloud_provisioning.provisioningvm",
            ),
        ),
    ]
