# Generated by Django 5.2 on 2026-09-19 12:53

import settings.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_vm_auto_provisioned_vm_cloud_provisioning_vm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sshcredential",
            name="key_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=settings.private_storage.PrivateCredentialStorage(),
                upload_to="inventory/ssh_keys/",
            ),
        ),
    ]
