# Generated by Django 5.2 on 2026-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runtime_env", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimeenvironment",
            name="cached_yaml_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/runtime_env_cache/"
            ),
        ),
        migrations.AddField(
            model_name="runtimeenvironment",
            name="raw_yaml",
            field=models.TextField(blank=True, default=""),
        ),
    ]
