# Generated by Django 5.2 on 2026-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runtime_env", "0002_runtimeenvironment_cached_yaml_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimeenvironment",
            name="command_groups",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
