# Generated by Django 5.2 on 2026-02-18 14:28

import runtime_env.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runtime_env", "0003_runtimeenvironment_command_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimeenvironment",
            name="serializer_rrt_config_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=runtime_env.models._rrt_config_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="runtimeenvironment",
            name="serializer_rrt_config_path",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="runtimeenvironment",
            name="serializer_rrt_config_raw_yaml",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="runtimeenvironment",
            name="uploaded_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="runtimeenvironment",
            name="cached_yaml_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=runtime_env.models._runtime_yaml_upload_to,
            ),
        ),
    ]
