# Generated by Django 5.2 on 2026-02-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runtime_env", "0004_runtimeenvironment_serializer_rrt_config_file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="runtimeenvironment",
            old_name="middleware",
            new_name="tags",
        ),
    ]
