# Generated by Django 5.2 on 2026-02-18 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilingGeneratedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("source_scenario_name", models.CharField(max_length=120)),
                ("source_refs", models.JSONField(blank=True, default=dict)),
                ("source_hashes", models.JSONField(blank=True, default=dict)),
                ("compiled_payload", models.JSONField(blank=True, default=dict)),
                ("compiled_yaml", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("READY", "Ready"), ("STARTED", "Started")],
                        default="READY",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiling_generated_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_profiling_generated_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_plans",
                        to="profiling_exps.profilingexperiment",
                    ),
                ),
            ],
            options={
                "unique_together": {("created_by", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProfilingGeneratedRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("stop_on_failure", models.BooleanField(default=True)),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("completed_runs", models.PositiveIntegerField(default=0)),
                ("failed_runs", models.PositiveIntegerField(default=0)),
                ("task_id", models.CharField(blank=True, default="", max_length=120)),
                ("results", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="profiling_exps.profilinggeneratedplan",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiling_generated_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["generated_plan", "status"],
                        name="profiling_e_generat_ab6469_idx",
                    ),
                    models.Index(
                        fields=["task_id"], name="profiling_e_task_id_edaba9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="profiling_e_created_8c6a24_idx"
                    ),
                ],
            },
        ),
    ]
