# Generated by Django 5.2 on 2026-02-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0002_profilinggeneratedplan_profilinggeneratedrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilinggeneratedrun",
            name="phase_action_execution_status",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
