# Generated by Django 5.2 on 2026-02-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0003_profilinggeneratedrun_phase_action_execution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilinggeneratedrun",
            name="collected_metrics_path",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
