# Generated by Django 5.2 on 2026-02-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0004_profilinggeneratedrun_collected_metrics_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilinggeneratedrun",
            name="metrics_collected",
            field=models.BooleanField(default=False),
        ),
    ]
