# Generated by Django 5.2 on 2026-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0005_profilinggeneratedrun_metrics_collected"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilinggeneratedrun",
            name="rrt_config_execution_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
