# Generated by Django 5.2 on 2026-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0006_profilinggeneratedrun_rrt_config_execution_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilinggeneratedrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPILED", "Compiled"),
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
