# Generated by Django 5.2 on 2026-02-19 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0007_alter_profilinggeneratedrun_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profilingexperiment",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilingexperiment",
            name="generated_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profilingexperiment",
            name="generated_source_hashes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profilingexperiment",
            name="generated_source_refs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profilingexperiment",
            name="generated_yaml",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profilingexperiment",
            name="run_check_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profilingexperiment",
            name="run_check_status",
            field=models.CharField(
                choices=[
                    ("NOT_RUN", "Not Run"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_RUN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profilingexperiment",
            name="run_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilingexperiment",
            name="total_generated_runs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProfilingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("stop_on_failure", models.BooleanField(default=True)),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("completed_runs", models.PositiveIntegerField(default=0)),
                ("failed_runs", models.PositiveIntegerField(default=0)),
                (
                    "compiled_payload_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("task_id", models.CharField(blank=True, default="", max_length=120)),
                ("results", models.JSONField(blank=True, default=list)),
                (
                    "phase_action_execution_status",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "rrt_config_execution_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "collected_metrics_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("metrics_collected", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="profiling_exps.profilingexperiment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiling_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProfilingGeneratedRun",
        ),
        migrations.DeleteModel(
            name="ProfilingGeneratedPlan",
        ),
        migrations.AddIndex(
            model_name="profilingrun",
            index=models.Index(
                fields=["experiment", "status"], name="profiling_e_experim_ec71f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilingrun",
            index=models.Index(
                fields=["task_id"], name="profiling_e_task_id_578f43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilingrun",
            index=models.Index(
                fields=["created_at"], name="profiling_e_created_890e95_idx"
            ),
        ),
    ]
