# Generated by Django 5.2 on 2026-02-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0008_remove_profilinggeneratedrun_generated_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilingrun",
            name="plan_run_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
