# Generated by Django 5.2 on 2026-02-20 10:39

from django.db import migrations, models


def _forward_status_cleanup(apps, schema_editor):
    ProfilingExperiment = apps.get_model("profiling_exps", "ProfilingExperiment")
    ProfilingRun = apps.get_model("profiling_exps", "ProfilingRun")

    run_statuses_by_exp: dict[int, set[str]] = {}
    for run in ProfilingRun.objects.all().only("experiment_id", "status"):
        status_set = run_statuses_by_exp.setdefault(run.experiment_id, set())
        status_set.add(str(run.status or ""))

    for exp in ProfilingExperiment.objects.all().only("id", "status", "generated_payload", "total_generated_runs"):
        payload = exp.generated_payload if isinstance(exp.generated_payload, dict) else {}
        payload_runs = payload.get("runs") if isinstance(payload.get("runs"), list) else []
        has_generated_plan = bool(int(exp.total_generated_runs or 0) > 0 and payload_runs)

        if not has_generated_plan:
            next_status = "NEW"
        else:
            run_statuses = run_statuses_by_exp.get(exp.id) or set()
            if "RUNNING" in run_statuses:
                next_status = "RUNNING"
            elif "PENDING" in run_statuses:
                next_status = "WAITING"
            elif run_statuses == {"SUCCEEDED"}:
                next_status = "FINISHED"
            elif "FAILED" in run_statuses:
                next_status = "ERROR"
            else:
                next_status = "WAITING"

        if exp.status != next_status:
            exp.status = next_status
            exp.save(update_fields=["status"])


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0009_profilingrun_plan_run_id"),
    ]

    operations = [
        migrations.RunPython(_forward_status_cleanup, _noop_reverse),
        migrations.AlterField(
            model_name="profilingexperiment",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Not Generated"),
                    ("WAITING", "Waiting To Run"),
                    ("RUNNING", "In Execution"),
                    ("FINISHED", "Finished"),
                    ("ERROR", "Error"),
                ],
                default="NEW",
                max_length=16,
            ),
        ),
    ]
