# Generated by Django 5.2 on 2026-02-21

from django.db import migrations, models


def _forward_backfill_generation_fields(apps, schema_editor):
    ProfilingExperiment = apps.get_model("profiling_exps", "ProfilingExperiment")
    ProfilingRun = apps.get_model("profiling_exps", "ProfilingRun")

    ProfilingRun.objects.filter(gen_version__isnull=True).update(gen_version=1)
    ProfilingRun.objects.filter(gen_version=0).update(gen_version=1)

    exp_ids_with_runs = set(ProfilingRun.objects.values_list("experiment_id", flat=True).distinct())
    for exp in ProfilingExperiment.objects.all().only("id", "current_gen_version"):
        next_version = 1 if exp.id in exp_ids_with_runs else 0
        if int(exp.current_gen_version or 0) != next_version:
            exp.current_gen_version = next_version
            exp.save(update_fields=["current_gen_version"])


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0010_alter_profilingexperiment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilingexperiment",
            name="current_gen_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profilingrun",
            name="gen_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(_forward_backfill_generation_fields, _noop_reverse),
        migrations.AddIndex(
            model_name="profilingrun",
            index=models.Index(fields=["experiment", "gen_version", "status"], name="profiling_e_experi_e88d39_idx"),
        ),
    ]
