# Generated by Django 5.2 on 2026-02-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0011_generation_versioning"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="profilingrun",
            new_name="profiling_e_experim_7420da_idx",
            old_name="profiling_e_experi_e88d39_idx",
        ),
        migrations.AddField(
            model_name="profilingrun",
            name="run_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
