# Generated by Django 5.2 on 2026-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiling_exps",
            "0012_rename_profiling_e_experi_e88d39_idx_profiling_e_experim_7420da_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profilingrun",
            name="characterization_parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
