# Generated by Django 5.2 on 2026-02-24 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0013_profilingrun_characterization_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilingComparision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiling_comparisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_profiling_comparisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilingComparisionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id_snapshot", models.PositiveIntegerField()),
                (
                    "experiment_name_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "plan_run_id_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "status_snapshot",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comparision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="profiling_exps.profilingcomparision",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comparision_rows",
                        to="profiling_exps.profilingrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="profilingcomparision",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="profiling_e_created_4f447d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profilingcomparision",
            unique_together={("created_by", "name")},
        ),
        migrations.AddIndex(
            model_name="profilingcomparisionrun",
            index=models.Index(
                fields=["comparision", "created_at"],
                name="profiling_e_compari_e75d0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profilingcomparisionrun",
            index=models.Index(
                fields=["run_id_snapshot"], name="profiling_e_run_id__155fbb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profilingcomparisionrun",
            unique_together={("comparision", "run_id_snapshot")},
        ),
    ]
