# Generated by Django 5.2 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling_exps", "0014_profilingcomparision_profilingcomparisionrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilingrun",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
