# Generated by Django 5.2 on 2026-02-16 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0007_alter_sshcredential_key_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudCredentialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("AZURE", "Azure")], default="AZURE", max_length=32
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("client_id_ref", models.CharField(max_length=128)),
                ("tenant_id_ref", models.CharField(max_length=128)),
                ("client_secret_ref", models.CharField(max_length=128)),
                ("subscription_ref", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_credential_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("created_by", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProvisioningRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "provider",
                    models.CharField(
                        choices=[("AZURE", "Azure")], default="AZURE", max_length=32
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("DELETING", "Deleting"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=120)),
                ("last_error", models.TextField(blank=True)),
                ("request_spec", models.JSONField(blank=True, default=dict)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provisioning_requests",
                        to="cloud_provisioning.cloudcredentialprofile",
                    ),
                ),
                (
                    "inventory_vm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloud_provisioning_requests",
                        to="inventory.vm",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_provisioning_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ssh_credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provisioning_requests",
                        to="inventory.sshcredential",
                    ),
                ),
            ],
            options={
                "unique_together": {("created_by", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProvisioningEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(default="INFO", max_length=16)),
                ("message", models.TextField()),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cloud_provisioning.provisioningrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
