# Generated by Django 5.2 on 2026-02-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_provisioning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningrequest",
            name="secret_file",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="provisioningrequest",
            name="credential_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provisioning_requests",
                to="cloud_provisioning.cloudcredentialprofile",
            ),
        ),
    ]
