# Generated by Django 5.2 on 2026-02-22 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_provisioning", "0002_provisioningrequest_secret_file_and_more"),
        ("inventory", "0010_vm_archived"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provisioningrequest",
            name="credential_profile",
        ),
        migrations.RemoveField(
            model_name="provisioningevent",
            name="request",
        ),
        migrations.AlterUniqueTogether(
            name="provisioningrequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="provisioningrequest",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="provisioningrequest",
            name="inventory_vm",
        ),
        migrations.RemoveField(
            model_name="provisioningrequest",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="provisioningrequest",
            name="ssh_credential",
        ),
        migrations.CreateModel(
            name="ProvisioningVM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "provider",
                    models.CharField(
                        choices=[("AZURE", "Azure")], default="AZURE", max_length=32
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("DELETING", "Deleting"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=120)),
                ("last_error", models.TextField(blank=True)),
                ("request_spec", models.JSONField(blank=True, default=dict)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_vms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_vm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloud_provisioning_vms",
                        to="inventory.vm",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_provisioning_vms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ssh_credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provisioning_vms",
                        to="inventory.sshcredential",
                    ),
                ),
            ],
            options={
                "unique_together": {("created_by", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProvisioningVMCheckRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=120)),
                ("check_data", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_vm_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_provisioning_vm_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provisioning_vm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_requests",
                        to="cloud_provisioning.provisioningvm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProvisioningVMEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(default="INFO", max_length=16)),
                ("message", models.TextField()),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provisioning_vm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cloud_provisioning.provisioningvm",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.DeleteModel(
            name="CloudCredentialProfile",
        ),
        migrations.DeleteModel(
            name="ProvisioningEvent",
        ),
        migrations.DeleteModel(
            name="ProvisioningRequest",
        ),
    ]
