# Generated by Django 5.2 on 2026-02-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cloud_provisioning",
            "0003_remove_provisioningrequest_credential_profile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningvm",
            name="raw_template",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="provisioningvm",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("DELETING", "Deleting"),
                    ("DELETED", "Deleted"),
                ],
                default="INITIALIZED",
                max_length=32,
            ),
        ),
    ]
