# Generated by Django 5.2 on 2026-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_provisioning", "0004_provisioningvm_raw_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningvm",
            name="instance_location",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="provisioningvm",
            name="instance_nic_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="provisioningvm",
            name="instance_power_state",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="provisioningvm",
            name="instance_provider_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="provisioningvm",
            name="instance_public_ip",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="provisioningvm",
            name="instance_size",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
