# Generated by Django 5.2 on 2026-02-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_provisioning", "0005_provisioningvm_instance_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningvm",
            name="group_name",
            field=models.CharField(default="default", max_length=120),
        ),
    ]
