# Generated by Django 5.2 on 2026-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_provisioning", "0007_provisioningvmstoprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisioningvm",
            name="icopa_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
