# Generated by Django 5.2 on 2026-09-15 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0011_vm_auto_provisioned_vm_cloud_provisioning_vm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProbeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_sec", models.PositiveIntegerField(default=5)),
                ("interval_sec", models.PositiveIntegerField(default=10)),
                ("window_count", models.PositiveIntegerField(default=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("STOPPED", "Stopped"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=120)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_vm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_probes",
                        to="inventory.vm",
                    ),
                ),
                (
                    "target_vm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_probes",
                        to="inventory.vm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProbeWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "measured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("source_address", models.CharField(max_length=255)),
                ("target_address", models.CharField(max_length=255)),
                ("metrics", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows",
                        to="micro_probing.probesession",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="probesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "RUNNING"])),
                fields=("created_by", "source_vm", "target_vm"),
                name="unique_active_probe_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="probesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_sec__gte", 1), ("duration_sec__lte", 10)),
                name="probe_duration_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="probesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval_sec__gte", 1), ("interval_sec__lte", 30)),
                name="probe_interval_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="probesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("window_count__gte", 1), ("window_count__lte", 60)),
                name="probe_window_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="probewindow",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence"), name="unique_probe_window"
            ),
        ),
    ]
