# Generated by Django 5.2 on 2026-02-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="check_status_actions",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("PASS", "Pass"),
                    ("FAIL", "Fail"),
                    ("SKIPPED", "Skipped"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="check_status_graph",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("PASS", "Pass"),
                    ("FAIL", "Fail"),
                    ("SKIPPED", "Skipped"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="check_status_node",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("PASS", "Pass"),
                    ("FAIL", "Fail"),
                    ("SKIPPED", "Skipped"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="last_validation_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="last_validation_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scenario",
            name="last_validation_task_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scenario",
            name="validation_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scenario",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                ],
                default="IDLE",
                max_length=16,
            ),
        ),
    ]
