# Generated by Django 5.2 on 2026-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0002_scenario_check_status_actions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="validation_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
