# Generated by Django 5.2 on 2026-02-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0003_scenario_validation_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="validation_trace",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
