# Generated by Django 5.2 on 2026-02-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0004_scenario_validation_trace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioValidationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=120)),
                ("check_actions", models.BooleanField(default=True)),
                ("check_nodes", models.BooleanField(default=True)),
                ("check_graph", models.BooleanField(default=True)),
                ("phase_name", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCEL_REQUESTED", "Cancel Requested"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("trace", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("cancel_requested", models.BooleanField(default=False)),
                ("canceled_by_clean", models.BooleanField(default=False)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_validation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_runs",
                        to="scenarios.scenario",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scenario", "status"],
                        name="scenarios_s_scenari_535d01_idx",
                    ),
                    models.Index(
                        fields=["task_id"], name="scenarios_s_task_id_5775cc_idx"
                    ),
                    models.Index(
                        fields=["requested_at"], name="scenarios_s_request_71ef58_idx"
                    ),
                ],
            },
        ),
    ]
