# Generated by Django 5.2 on 2026-02-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0005_scenariovalidation_scenariovalidationrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariovalidationrun",
            name="probe_metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
