# Generated by Django 5.2 on 2026-02-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0006_scenariovalidationrun_probe_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariovalidationrun",
            name="metrics_local_dir",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="scenariovalidationrun",
            name="metrics_remote_dir",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="scenariovalidationrun",
            name="need_to_collect_metrics",
            field=models.BooleanField(default=False),
        ),
    ]
