# Generated by Django 5.2 on 2026-02-18 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_vm_managed_containers_vm_system_info_and_more"),
        ("scenarios", "0007_scenariovalidationrun_metrics_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioValidationRunVM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(max_length=120)),
                ("phase_name", models.CharField(blank=True, default="", max_length=120)),
                ("remote_dir", models.CharField(blank=True, default="", max_length=512)),
                ("local_dir", models.CharField(blank=True, default="", max_length=512)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("collected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vm_metrics",
                        to="scenarios.scenariovalidationrun",
                    ),
                ),
                (
                    "vm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenario_validation_vm_metrics",
                        to="inventory.vm",
                    ),
                ),
            ],
            options={
                "unique_together": {("run", "node_name")},
                "indexes": [
                    models.Index(
                        fields=["run", "node_name"],
                        name="scenarios_s_run_id_172018_idx",
                    ),
                    models.Index(
                        fields=["created_at"],
                        name="scenarios_s_created_0f7ddb_idx",
                    ),
                ],
            },
        ),
    ]
